### ISSUE TITLE
build failed  -- error[E0583]: file not found for module `montgomery`

### ISSUE THREAD

**Issue by zhaohansprt** [OmnijarBots/beryllium#5]
> Compiling interfaces v0.0.3                                                  
>    Compiling ring v0.12.1
>    Compiling cryptobox v1.0.0 (https://github.com/wireapp/cryptobox?branch=develop#ec45a50c)
>    Compiling beryllium v0.1.0 (file:///home/rust/src)
> error[E0583]: file not found for module `montgomery`
>   --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.12.1/src/arithmetic/arithmetic.rs:15:9
>    |
> 15 | pub mod montgomery;
>    |         ^^^^^^^^^^
>    |
>    = help: name the file either arithmetic/montgomery.rs or arithmetic/montgomery/mod.rs inside the directory "/home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.12.1/src/arithmetic"
> 
> error: aborting due to previous error
> 
> error: Could not compile `ring`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed

i can't find where dep on the ring ,the ring offical said this should be fixed by the 
https://github.com/briansmith/ring/issues/598

**Comment by siilime** [comment]
Thanks @zhaohansprt. Will look into this ASAP and bump the version. Thanks for raising this.

**Comment by wafflespeanut** [comment]
This has been fixed in ce4136e - will reflect soon in this repo.

**Comment by siilime** [comment]
Merged as of 3a1aa45.
